server:
  host: "0.0.0.0"
  httpPort: 9001
  mqPort: 9002

nats:
  url: "nats://127.0.0.1:4222"

log:
  level: "info"
  logFile: "lobby"
  maxSize: 500    # 单文件最大 MB
  maxAge: 30      # 旧日志保留天数

mongo:
  uri: "mongodb://127.0.0.1:27017"
  database: "lobby"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
