services:
  lobby:
    container_name: lobby-server
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: "no"
    ports:
      - "9001:9001"
      - "9002:9002"
    volumes:
      - ./logs:/app/logs
      - ./config.local.yaml:/app/config.yaml:ro
    networks:
      - lobby-net
      - mongo-net
      - redis-net
      - nats-net
      - etcd-net

networks:
  lobby-net:
    name: lobby-net
    driver: bridge
  mongo-net:
    external: true
  redis-net:
    external: true
  nats-net:
    external: true
  etcd-net:
    external: true
