// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.9.1
// source: gate/gate.proto

package gate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "github.com/go-meridian/lobby/model/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gate → Lobby 请求消息封装
type GateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=connId,proto3" json:"connId,omitempty"`       // WebSocket 连接 ID
	RequestId     uint64                 `protobuf:"varint,2,opt,name=requestId,proto3" json:"requestId,omitempty"` // 请求 ID（匹配响应）
	MsgId         uint32                 `protobuf:"varint,3,opt,name=msgId,proto3" json:"msgId,omitempty"`         // 消息类型 ID
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`      // 业务 Proto 序列化字节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateRequest) Reset() {
	*x = GateRequest{}
	mi := &file_gate_gate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateRequest) ProtoMessage() {}

func (x *GateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateRequest.ProtoReflect.Descriptor instead.
func (*GateRequest) Descriptor() ([]byte, []int) {
	return file_gate_gate_proto_rawDescGZIP(), []int{0}
}

func (x *GateRequest) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *GateRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *GateRequest) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Lobby → Gate 响应消息封装
type GateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=connId,proto3" json:"connId,omitempty"`       // WebSocket 连接 ID
	RequestId     uint64                 `protobuf:"varint,2,opt,name=requestId,proto3" json:"requestId,omitempty"` // 请求 ID
	MsgId         uint32                 `protobuf:"varint,3,opt,name=msgId,proto3" json:"msgId,omitempty"`         // 消息类型 ID
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`      // 业务 Proto 序列化字节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateResponse) Reset() {
	*x = GateResponse{}
	mi := &file_gate_gate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateResponse) ProtoMessage() {}

func (x *GateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateResponse.ProtoReflect.Descriptor instead.
func (*GateResponse) Descriptor() ([]byte, []int) {
	return file_gate_gate_proto_rawDescGZIP(), []int{1}
}

func (x *GateResponse) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *GateResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *GateResponse) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GateResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Lobby → Gate 推送消息（无 requestId，主动推送）
type GatePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=connId,proto3" json:"connId,omitempty"`  // WebSocket 连接 ID（0=广播）
	MsgId         uint32                 `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`    // 消息类型 ID
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // 业务 Proto 序列化字节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatePush) Reset() {
	*x = GatePush{}
	mi := &file_gate_gate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatePush) ProtoMessage() {}

func (x *GatePush) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatePush.ProtoReflect.Descriptor instead.
func (*GatePush) Descriptor() ([]byte, []int) {
	return file_gate_gate_proto_rawDescGZIP(), []int{2}
}

func (x *GatePush) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *GatePush) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GatePush) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 认证请求（Gate 内部处理或转发给 Lobby）
type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ServiceToken  string                 `protobuf:"bytes,2,opt,name=serviceToken,proto3" json:"serviceToken,omitempty"`
	SecurityKey   string                 `protobuf:"bytes,3,opt,name=securityKey,proto3" json:"securityKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_gate_gate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_gate_gate_proto_rawDescGZIP(), []int{3}
}

func (x *AuthReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AuthReq) GetServiceToken() string {
	if x != nil {
		return x.ServiceToken
	}
	return ""
}

func (x *AuthReq) GetSecurityKey() string {
	if x != nil {
		return x.SecurityKey
	}
	return ""
}

// 认证响应
type AuthRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       *common.ErrMsg         `protobuf:"bytes,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRsp) Reset() {
	*x = AuthRsp{}
	mi := &file_gate_gate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRsp) ProtoMessage() {}

func (x *AuthRsp) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRsp.ProtoReflect.Descriptor instead.
func (*AuthRsp) Descriptor() ([]byte, []int) {
	return file_gate_gate_proto_rawDescGZIP(), []int{4}
}

func (x *AuthRsp) GetRetCode() *common.ErrMsg {
	if x != nil {
		return x.RetCode
	}
	return nil
}

func (x *AuthRsp) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 连接建立通知（Gate → Lobby）
type ConnOpenNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=connId,proto3" json:"connId,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=clientIp,proto3" json:"clientIp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnOpenNotify) Reset() {
	*x = ConnOpenNotify{}
	mi := &file_gate_gate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnOpenNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnOpenNotify) ProtoMessage() {}

func (x *ConnOpenNotify) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnOpenNotify.ProtoReflect.Descriptor instead.
func (*ConnOpenNotify) Descriptor() ([]byte, []int) {
	return file_gate_gate_proto_rawDescGZIP(), []int{5}
}

func (x *ConnOpenNotify) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *ConnOpenNotify) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ConnOpenNotify) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// 连接断开通知（Gate → Lobby）
type ConnCloseNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=connId,proto3" json:"connId,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnCloseNotify) Reset() {
	*x = ConnCloseNotify{}
	mi := &file_gate_gate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnCloseNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnCloseNotify) ProtoMessage() {}

func (x *ConnCloseNotify) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnCloseNotify.ProtoReflect.Descriptor instead.
func (*ConnCloseNotify) Descriptor() ([]byte, []int) {
	return file_gate_gate_proto_rawDescGZIP(), []int{6}
}

func (x *ConnCloseNotify) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *ConnCloseNotify) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ConnCloseNotify) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 限流请求（Gate 内部）
type RateLimitCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MsgId         uint32                 `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitCheck) Reset() {
	*x = RateLimitCheck{}
	mi := &file_gate_gate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitCheck) ProtoMessage() {}

func (x *RateLimitCheck) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitCheck.ProtoReflect.Descriptor instead.
func (*RateLimitCheck) Descriptor() ([]byte, []int) {
	return file_gate_gate_proto_rawDescGZIP(), []int{7}
}

func (x *RateLimitCheck) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RateLimitCheck) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

// 消息路由信息（用于 NATS 主题）
type MsgRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueGroup    string                 `protobuf:"bytes,1,opt,name=queueGroup,proto3" json:"queueGroup,omitempty"` // NATS 队列组名
	CmdId         uint32                 `protobuf:"varint,2,opt,name=cmdId,proto3" json:"cmdId,omitempty"`          // 命令 ID（用于路由到具体处理器）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRoute) Reset() {
	*x = MsgRoute{}
	mi := &file_gate_gate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRoute) ProtoMessage() {}

func (x *MsgRoute) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRoute.ProtoReflect.Descriptor instead.
func (*MsgRoute) Descriptor() ([]byte, []int) {
	return file_gate_gate_proto_rawDescGZIP(), []int{8}
}

func (x *MsgRoute) GetQueueGroup() string {
	if x != nil {
		return x.QueueGroup
	}
	return ""
}

func (x *MsgRoute) GetCmdId() uint32 {
	if x != nil {
		return x.CmdId
	}
	return 0
}

var File_gate_gate_proto protoreflect.FileDescriptor

const file_gate_gate_proto_rawDesc = "" +
	"\n" +
	"\x0fgate/gate.proto\x12\x04gate\x1a\x13common/common.proto\"s\n" +
	"\vGateRequest\x12\x16\n" +
	"\x06connId\x18\x01 \x01(\x04R\x06connId\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\x04R\trequestId\x12\x14\n" +
	"\x05msgId\x18\x03 \x01(\rR\x05msgId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"t\n" +
	"\fGateResponse\x12\x16\n" +
	"\x06connId\x18\x01 \x01(\x04R\x06connId\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\x04R\trequestId\x12\x14\n" +
	"\x05msgId\x18\x03 \x01(\rR\x05msgId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"R\n" +
	"\bGatePush\x12\x16\n" +
	"\x06connId\x18\x01 \x01(\x04R\x06connId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\rR\x05msgId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"a\n" +
	"\aAuthReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\"\n" +
	"\fserviceToken\x18\x02 \x01(\tR\fserviceToken\x12 \n" +
	"\vsecurityKey\x18\x03 \x01(\tR\vsecurityKey\"E\n" +
	"\aAuthRsp\x12(\n" +
	"\aretCode\x18\x01 \x01(\v2\x0e.common.ErrMsgR\aretCode\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"V\n" +
	"\x0eConnOpenNotify\x12\x16\n" +
	"\x06connId\x18\x01 \x01(\x04R\x06connId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x1a\n" +
	"\bclientIp\x18\x03 \x01(\tR\bclientIp\"S\n" +
	"\x0fConnCloseNotify\x12\x16\n" +
	"\x06connId\x18\x01 \x01(\x04R\x06connId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"8\n" +
	"\x0eRateLimitCheck\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\rR\x05msgId\"@\n" +
	"\bMsgRoute\x12\x1e\n" +
	"\n" +
	"queueGroup\x18\x01 \x01(\tR\n" +
	"queueGroup\x12\x14\n" +
	"\x05cmdId\x18\x02 \x01(\rR\x05cmdIdB\fZ\n" +
	"proto/gateb\x06proto3"

var (
	file_gate_gate_proto_rawDescOnce sync.Once
	file_gate_gate_proto_rawDescData []byte
)

func file_gate_gate_proto_rawDescGZIP() []byte {
	file_gate_gate_proto_rawDescOnce.Do(func() {
		file_gate_gate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gate_gate_proto_rawDesc), len(file_gate_gate_proto_rawDesc)))
	})
	return file_gate_gate_proto_rawDescData
}

var file_gate_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gate_gate_proto_goTypes = []any{
	(*GateRequest)(nil),     // 0: gate.GateRequest
	(*GateResponse)(nil),    // 1: gate.GateResponse
	(*GatePush)(nil),        // 2: gate.GatePush
	(*AuthReq)(nil),         // 3: gate.AuthReq
	(*AuthRsp)(nil),         // 4: gate.AuthRsp
	(*ConnOpenNotify)(nil),  // 5: gate.ConnOpenNotify
	(*ConnCloseNotify)(nil), // 6: gate.ConnCloseNotify
	(*RateLimitCheck)(nil),  // 7: gate.RateLimitCheck
	(*MsgRoute)(nil),        // 8: gate.MsgRoute
	(*common.ErrMsg)(nil),   // 9: common.ErrMsg
}
var file_gate_gate_proto_depIdxs = []int32{
	9, // 0: gate.AuthRsp.retCode:type_name -> common.ErrMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gate_gate_proto_init() }
func file_gate_gate_proto_init() {
	if File_gate_gate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gate_gate_proto_rawDesc), len(file_gate_gate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gate_gate_proto_goTypes,
		DependencyIndexes: file_gate_gate_proto_depIdxs,
		MessageInfos:      file_gate_gate_proto_msgTypes,
	}.Build()
	File_gate_gate_proto = out.File
	file_gate_gate_proto_goTypes = nil
	file_gate_gate_proto_depIdxs = nil
}
