// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.9.1
// source: packet/MsgId.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息 ID 枚举定义
type MsgId int32

const (
	// ============ 通用 ============
	MsgId_MSG_UNKNOWN MsgId = 0
	// ============ 系统消息 (1xxx) ============
	MsgId_MSG_HEARTBEAT_REQ MsgId = 1001 // 心跳请求
	MsgId_MSG_HEARTBEAT_RSP MsgId = 1002 // 心跳响应
	// ============ 账号消息 (2xxx) ============
	MsgId_MSG_LOGIN_REQ      MsgId = 2001 // 登录请求
	MsgId_MSG_LOGIN_RSP      MsgId = 2002 // 登录响应
	MsgId_MSG_LOGIN_TEST_REQ MsgId = 2003 // 测试登录请求
	MsgId_MSG_LOGIN_TEST_RSP MsgId = 2004 // 测试登录响应
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0:    "MSG_UNKNOWN",
		1001: "MSG_HEARTBEAT_REQ",
		1002: "MSG_HEARTBEAT_RSP",
		2001: "MSG_LOGIN_REQ",
		2002: "MSG_LOGIN_RSP",
		2003: "MSG_LOGIN_TEST_REQ",
		2004: "MSG_LOGIN_TEST_RSP",
	}
	MsgId_value = map[string]int32{
		"MSG_UNKNOWN":        0,
		"MSG_HEARTBEAT_REQ":  1001,
		"MSG_HEARTBEAT_RSP":  1002,
		"MSG_LOGIN_REQ":      2001,
		"MSG_LOGIN_RSP":      2002,
		"MSG_LOGIN_TEST_REQ": 2003,
		"MSG_LOGIN_TEST_RSP": 2004,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_MsgId_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_packet_MsgId_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_packet_MsgId_proto_rawDescGZIP(), []int{0}
}

var File_packet_MsgId_proto protoreflect.FileDescriptor

const file_packet_MsgId_proto_rawDesc = "" +
	"\n" +
	"\x12packet/MsgId.proto\x12\x06packet*\xa2\x01\n" +
	"\x05MsgId\x12\x0f\n" +
	"\vMSG_UNKNOWN\x10\x00\x12\x16\n" +
	"\x11MSG_HEARTBEAT_REQ\x10\xe9\a\x12\x16\n" +
	"\x11MSG_HEARTBEAT_RSP\x10\xea\a\x12\x12\n" +
	"\rMSG_LOGIN_REQ\x10\xd1\x0f\x12\x12\n" +
	"\rMSG_LOGIN_RSP\x10\xd2\x0f\x12\x17\n" +
	"\x12MSG_LOGIN_TEST_REQ\x10\xd3\x0f\x12\x17\n" +
	"\x12MSG_LOGIN_TEST_RSP\x10\xd4\x0fB\x0eZ\fproto/packetb\x06proto3"

var (
	file_packet_MsgId_proto_rawDescOnce sync.Once
	file_packet_MsgId_proto_rawDescData []byte
)

func file_packet_MsgId_proto_rawDescGZIP() []byte {
	file_packet_MsgId_proto_rawDescOnce.Do(func() {
		file_packet_MsgId_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_MsgId_proto_rawDesc), len(file_packet_MsgId_proto_rawDesc)))
	})
	return file_packet_MsgId_proto_rawDescData
}

var file_packet_MsgId_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packet_MsgId_proto_goTypes = []any{
	(MsgId)(0), // 0: packet.MsgId
}
var file_packet_MsgId_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_MsgId_proto_init() }
func file_packet_MsgId_proto_init() {
	if File_packet_MsgId_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_MsgId_proto_rawDesc), len(file_packet_MsgId_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_MsgId_proto_goTypes,
		DependencyIndexes: file_packet_MsgId_proto_depIdxs,
		EnumInfos:         file_packet_MsgId_proto_enumTypes,
	}.Build()
	File_packet_MsgId_proto = out.File
	file_packet_MsgId_proto_goTypes = nil
	file_packet_MsgId_proto_depIdxs = nil
}
