// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.9.1
// source: account/account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "github.com/go-meridian/lobby/model/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录请求
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	GameId        int32                  `protobuf:"varint,4,opt,name=gameId,proto3" json:"gameId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_account_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *LoginReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *LoginReq) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *LoginReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

// 登录响应
type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       *common.ErrMsg         `protobuf:"bytes,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ServiceToken  string                 `protobuf:"bytes,3,opt,name=serviceToken,proto3" json:"serviceToken,omitempty"`
	OpenId        string                 `protobuf:"bytes,4,opt,name=openId,proto3" json:"openId,omitempty"`
	SecurityKey   string                 `protobuf:"bytes,5,opt,name=securityKey,proto3" json:"securityKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_account_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRsp) GetRetCode() *common.ErrMsg {
	if x != nil {
		return x.RetCode
	}
	return nil
}

func (x *LoginRsp) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginRsp) GetServiceToken() string {
	if x != nil {
		return x.ServiceToken
	}
	return ""
}

func (x *LoginRsp) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *LoginRsp) GetSecurityKey() string {
	if x != nil {
		return x.SecurityKey
	}
	return ""
}

// 测试登录请求
type LoginTestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginTestReq) Reset() {
	*x = LoginTestReq{}
	mi := &file_account_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginTestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTestReq) ProtoMessage() {}

func (x *LoginTestReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTestReq.ProtoReflect.Descriptor instead.
func (*LoginTestReq) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{2}
}

func (x *LoginTestReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginTestReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 测试登录响应
type LoginTestRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       *common.ErrMsg         `protobuf:"bytes,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ServiceToken  string                 `protobuf:"bytes,3,opt,name=serviceToken,proto3" json:"serviceToken,omitempty"`
	OpenId        string                 `protobuf:"bytes,4,opt,name=openId,proto3" json:"openId,omitempty"`
	SecurityKey   string                 `protobuf:"bytes,5,opt,name=securityKey,proto3" json:"securityKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginTestRsp) Reset() {
	*x = LoginTestRsp{}
	mi := &file_account_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginTestRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTestRsp) ProtoMessage() {}

func (x *LoginTestRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTestRsp.ProtoReflect.Descriptor instead.
func (*LoginTestRsp) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{3}
}

func (x *LoginTestRsp) GetRetCode() *common.ErrMsg {
	if x != nil {
		return x.RetCode
	}
	return nil
}

func (x *LoginTestRsp) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginTestRsp) GetServiceToken() string {
	if x != nil {
		return x.ServiceToken
	}
	return ""
}

func (x *LoginTestRsp) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *LoginTestRsp) GetSecurityKey() string {
	if x != nil {
		return x.SecurityKey
	}
	return ""
}

// Token信息
type ServiceToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` // 固定字符串: "st"
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	CreateTs      int64                  `protobuf:"varint,3,opt,name=createTs,proto3" json:"createTs,omitempty"` // 时间戳(毫秒)
	SecurityKey   string                 `protobuf:"bytes,4,opt,name=securityKey,proto3" json:"securityKey,omitempty"`
	Appid         uint32                 `protobuf:"varint,5,opt,name=appid,proto3" json:"appid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceToken) Reset() {
	*x = ServiceToken{}
	mi := &file_account_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceToken) ProtoMessage() {}

func (x *ServiceToken) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceToken.ProtoReflect.Descriptor instead.
func (*ServiceToken) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceToken) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ServiceToken) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ServiceToken) GetCreateTs() int64 {
	if x != nil {
		return x.CreateTs
	}
	return 0
}

func (x *ServiceToken) GetSecurityKey() string {
	if x != nil {
		return x.SecurityKey
	}
	return ""
}

func (x *ServiceToken) GetAppid() uint32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

var File_account_account_proto protoreflect.FileDescriptor

const file_account_account_proto_rawDesc = "" +
	"\n" +
	"\x15account/account.proto\x12\aaccount\x1a\x13common/common.proto\"t\n" +
	"\bLoginReq\x12\x16\n" +
	"\x06openId\x18\x01 \x01(\tR\x06openId\x12\x1a\n" +
	"\bnickName\x18\x02 \x01(\tR\bnickName\x12\x1c\n" +
	"\tavatarUrl\x18\x03 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06gameId\x18\x04 \x01(\x05R\x06gameId\"\xa4\x01\n" +
	"\bLoginRsp\x12(\n" +
	"\aretCode\x18\x01 \x01(\v2\x0e.common.ErrMsgR\aretCode\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\"\n" +
	"\fserviceToken\x18\x03 \x01(\tR\fserviceToken\x12\x16\n" +
	"\x06openId\x18\x04 \x01(\tR\x06openId\x12 \n" +
	"\vsecurityKey\x18\x05 \x01(\tR\vsecurityKey\"D\n" +
	"\fLoginTestReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa8\x01\n" +
	"\fLoginTestRsp\x12(\n" +
	"\aretCode\x18\x01 \x01(\v2\x0e.common.ErrMsgR\aretCode\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\"\n" +
	"\fserviceToken\x18\x03 \x01(\tR\fserviceToken\x12\x16\n" +
	"\x06openId\x18\x04 \x01(\tR\x06openId\x12 \n" +
	"\vsecurityKey\x18\x05 \x01(\tR\vsecurityKey\"\x8e\x01\n" +
	"\fServiceToken\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x1a\n" +
	"\bcreateTs\x18\x03 \x01(\x03R\bcreateTs\x12 \n" +
	"\vsecurityKey\x18\x04 \x01(\tR\vsecurityKey\x12\x14\n" +
	"\x05appid\x18\x05 \x01(\rR\x05appidB\x0fZ\rproto/accountb\x06proto3"

var (
	file_account_account_proto_rawDescOnce sync.Once
	file_account_account_proto_rawDescData []byte
)

func file_account_account_proto_rawDescGZIP() []byte {
	file_account_account_proto_rawDescOnce.Do(func() {
		file_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_account_proto_rawDesc), len(file_account_account_proto_rawDesc)))
	})
	return file_account_account_proto_rawDescData
}

var file_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_account_account_proto_goTypes = []any{
	(*LoginReq)(nil),      // 0: account.LoginReq
	(*LoginRsp)(nil),      // 1: account.LoginRsp
	(*LoginTestReq)(nil),  // 2: account.LoginTestReq
	(*LoginTestRsp)(nil),  // 3: account.LoginTestRsp
	(*ServiceToken)(nil),  // 4: account.ServiceToken
	(*common.ErrMsg)(nil), // 5: common.ErrMsg
}
var file_account_account_proto_depIdxs = []int32{
	5, // 0: account.LoginRsp.retCode:type_name -> common.ErrMsg
	5, // 1: account.LoginTestRsp.retCode:type_name -> common.ErrMsg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_account_account_proto_init() }
func file_account_account_proto_init() {
	if File_account_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_account_proto_rawDesc), len(file_account_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_account_proto_goTypes,
		DependencyIndexes: file_account_account_proto_depIdxs,
		MessageInfos:      file_account_account_proto_msgTypes,
	}.Build()
	File_account_account_proto = out.File
	file_account_account_proto_goTypes = nil
	file_account_account_proto_depIdxs = nil
}
